infoproject/infoapp/urls.py
# from django.contrib import admin
from django.urls import path
from infoapp import views
# from .models import *
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
app_name = 'infoapp'
urlpatterns = [
   
    # path('meter-data-calculation', views.meter_data_calculation,
    #      name='meter_data_calculation'),
    path('', views.simple_upload, name='data-import'),
    path('delete-page', views.delete_page, name='delete-page'),
    path('data-delete', views.data_delete, name='data_delete'),
    path('view-result', views.view_result, name='view-result'),
    path('meter-data-calculation', views.meter_data_calculation, name='meter-data-calculation'),
    path('home-page', views.home_page, name='home-page'),
    path('user-login', views.user_login, name='user-login'),
    path('user-logout', views.user_logout, name='user-logout'),
    path('meter-info', views.meter_info, name='meter-info'),
    path('upload-history', views.upload_history, name='upload-history'),
    

    
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

infoproject/infoproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('infoapp.urls')),
]

infoproject/templates/base.html
<!DOCTYPE html>
<html>
<title>SAIDI-SAIFI</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="/static/css/styles.css">
<style>
html,body,h1,h2,h3,h4,h5 {font-family: "Raleway", sans-serif}
</style>
<body class="w3-light-grey">

<!-- Top container -->
<div class="w3-bar w3-top w3-black w3-large" style="z-index:4">
  <button class="w3-bar-item w3-button w3-hide-large w3-hover-none w3-hover-text-light-grey" onclick="w3_open();"><i class="fa fa-bars"></i>  Menu</button>
  <span class="w3-bar-item w3-right">
    <h4>{{ user.first_name}}    {{user.last_name}}</h4>
  </span>
  
</div>

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;" id="mySidebar"><br>
  <div class="w3-container">
    <h5>SAIDI-SAIFI</h5>
  </div>
  
  <div class="w3-bar-block">
    <i class="fas fa-trash-alt"></i>
    <a href="{% url 'infoapp:home-page' %}" class="w3-bar-item w3-button w3-padding w3-blue"><i class="fa fa-users fa-fw"></i>Home</a>
    <a href="{% url 'infoapp:data-import' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-eye fa-fw"></i> Data Upload</a>
    <a href="{% url 'infoapp:upload-history' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-eye fa-fw"></i> Upload History</a>
    <a href="{% url 'infoapp:view-result' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-users fa-fw"></i>Result</a>
    <a href="{% url 'infoapp:delete-page' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bank fa-fw"></i>  Data Delete</a>
    <a href="{% url 'infoapp:user-logout' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-diamond fa-fw"></i>  Logout</a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bell fa-fw"></i>  Feeder</a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-history fa-fw"></i>  Consummer</a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-cog fa-fw"></i>  Settings</a><br><br>

  </div>
</nav>


<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:300px;margin-top:43px;">

  <!-- Header -->
  <header class="w3-container" style="padding-top:22px">
    <h5><b><i class="fa fa-dashboard"></i> My Dashboard</b></h5>
  </header>


  <!-- ------------------FOr ME------------------ -->
  <section class="w3-container w3-padding-16 w3-light-grey" style="height: 480px;">
    {% block content %}
    {% endblock %}
  </section>



  <!-- Footer -->
  <footer class="w3-container w3-padding-16 w3-light-grey d-flex justify-content-center" >

  </footer>

  <!-- End page content -->
</div>

<script>
// Get the Sidebar
var mySidebar = document.getElementById("mySidebar");

// Get the DIV with overlay effect
var overlayBg = document.getElementById("myOverlay");

// Toggle between showing and hiding the sidebar, and add overlay effect
function w3_open() {
  if (mySidebar.style.display === 'block') {
    mySidebar.style.display = 'none';
    overlayBg.style.display = "none";
  } else {
    mySidebar.style.display = 'block';
    overlayBg.style.display = "block";
  }
}

// Close the sidebar with the close button
function w3_close() {
  mySidebar.style.display = "none";
  overlayBg.style.display = "none";
}
</script>

</body>
</html>

infoproject/templates/data-delete.html
{% extends 'base.html' %}
{% block content %}


<div class="container ">
    <div class="row m-auto">
        <div class="col-6 m-auto">
            {% if msg %}
<div class="alert alert-success" role="alert">
    {{msg}}
</div>

{% endif %}



<br>

<a href="{% url 'infoapp:data_delete' %}"><button class="btn btn-secondary">Previous Data Delete</button></a>


        </div>
    </div>
</div>

{% endblock %}

infoproject/templates/export_report.html
<html>
    <head>

    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="com-md-5 m-auto">
                  <table>
          
                    <tr>
                      <td>
                        <label>Month: </label>
                        <select class="mdb-select md-form" >
                          <option selected>select</option>
                          <option value="1">January</option>
                          <option value="2">February</option>
                          <option value="3">March</option>
                          <option value="4">April</option>
                          <option value="5">May</option>
                          <option value="6">June</option>
                          <option value="7">July</option>
                          <option value="8">August</option>
                          <option value="9">September</option>
                          <option value="10">October</option>
                          <option value="11">November</option>
                          <option value="11">December</option>
                        </select>
                      
                      
                      </td>
                      <td>
                        <label>Year: </label>
                        <select class="mdb-select md-form">
                          <option selected>select</option>
                          <option value="2020">2020</option>
                          <option value="2021">2021</option>
                          <option value="2022">2022</option>
                        </select>
                    
                      
                      </td>
                     
                      <td> &nbsp;  &nbsp;<button type="button" style="height: 30px; text-align: center;" class="btn btn-secondary btn-sm">Download</button></td>
                    </tr>
                  </table>
                </div>
            </div>
          </div>
    </body>
</html>

infoproject/templates/home_page.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row m-auto">
        <div class="col-12">
            <h1>Welcome to SAIDI-SAIFI Calculation System</h1>
            <br>
            <div class="list-group">
                <a href="#" class="list-group-item list-group-item-dark">
                  <strong>Instruction:</strong> 
                </a>
                <a href="#" class="list-group-item list-group-item-action">Data upload must be .xlxs extention</a>
                <a href="#" class="list-group-item list-group-item-action">Be upload excel file insert column at first</a>
                <a href="#" class="list-group-item list-group-item-action">After data calculation delte previous data</a>
                
              </div>
            
        </div>
    </div>
</div>

{% endblock %}

infoproject/templates/m_dc_consumer.html
<!DOCTYPE html>
<html>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
html,body,h1,h2,h3,h4,h5 {font-family: "Raleway", sans-serif}
</style>
<body class="w3-light-grey">

<!-- Top container -->
<div class="w3-bar w3-top w3-black w3-large" style="z-index:4">
  <button class="w3-bar-item w3-button w3-hide-large w3-hover-none w3-hover-text-light-grey" onclick="w3_open();"><i class="fa fa-bars"></i>  Menu</button>
  <span class="w3-bar-item w3-right">Logo</span>
</div>

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;" id="mySidebar"><br>
  <div class="w3-container">
    <h5>SAIDI-SAIFI</h5>
  </div>
  <div class="w3-bar-block">
    <a href="#" class="w3-bar-item w3-button w3-padding-16 w3-hide-large w3-dark-grey w3-hover-black" onclick="w3_close()" title="close menu"><i class="fa fa-remove fa-fw"></i>  Close Menu</a>
    <a href="#" class="w3-bar-item w3-button w3-padding w3-blue"><i class="fa fa-users fa-fw"></i>  Overview</a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-eye fa-fw"></i>  Views</a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-users fa-fw"></i>  Traffic</a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bullseye fa-fw"></i>  Geo</a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-diamond fa-fw"></i>  Orders</a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bell fa-fw"></i>  News</a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bank fa-fw"></i>  General</a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-history fa-fw"></i>  History</a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-cog fa-fw"></i>  Settings</a><br><br>
  </div>
</nav>


<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:300px;margin-top:43px;">

  <!-- Header -->
  <header class="w3-container" style="padding-top:22px">
    <h5><b><i class="fa fa-dashboard"></i> My Dashboard</b></h5>
  </header>


  <!-- ------------------FOr ME------------------ -->
  <section class="w3-container w3-padding-16 w3-light-grey">
    Data
  </section>



  <!-- Footer -->
  <footer class="w3-container w3-padding-16 w3-light-grey">
    <p>Developed by: </p>
    <p>@c-2021</p>
  </footer>

  <!-- End page content -->
</div>

<script>
// Get the Sidebar
var mySidebar = document.getElementById("mySidebar");

// Get the DIV with overlay effect
var overlayBg = document.getElementById("myOverlay");

// Toggle between showing and hiding the sidebar, and add overlay effect
function w3_open() {
  if (mySidebar.style.display === 'block') {
    mySidebar.style.display = 'none';
    overlayBg.style.display = "none";
  } else {
    mySidebar.style.display = 'block';
    overlayBg.style.display = "block";
  }
}

// Close the sidebar with the close button
function w3_close() {
  mySidebar.style.display = "none";
  overlayBg.style.display = "none";
}
</script>

</body>
</html>

infoproject/templates/meter-info.html
{% extends 'base.html' %}
{% block content%}

<div class="container">
  <div class="row">
    <div class="col-3 m-auto">


          <!-- <form method="post">
            {% csrf_token %}
            
            <p>Meter No: <input type="text" name="m_no"></p>
            <p>Month: <input type="text" name="month"></p>
            <p>Year: <input type="text" name="year"></p>
            <button class="btn btn-secondary" type="submit">Submit</button>
          </form> -->
          <form method="POST">
            {% csrf_token %}
            <label for="s">Substation:</label>

            <select class="form form-control bg-light col-md-6" id="s" name="s_info" required>
              <option value="">---------</option>
              {% for s_s in s_s %}
              
              <option value="{{s_s.id}}">{{s_s}}</option>
              {%endfor %}

            </select>
            <br>
            {{data_form}}
            <!-- <div class="form-group">
              <label for="exampleInputEmail1">Month:</label>
              <input type="text" name="month" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" required placeholder="Please enter month">
               <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
             </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Year:</label>
              <input type="text" name="year" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" required placeholder="Please enter year">
              <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
            </div> 
            -->

            <br>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>

          <br>

    </div>
  </div>
</div>

{% endblock %}

infoproject/templates/monthly-result.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
  <div class="row">
    <div class="col m-auto">


        <table class="table table-bordered">
            <h5>Sunamganj PBS</h5>
            <h6>Month of June-2021</h6>
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Substation</th>
                <th scope="col">Feeder</th>
                <th scope="col">Total No of Interruption</th>
                <th scope="col">Total Time of Interruption</th>
                <th scope="col">SAIDI In A Feeder</th>
                <th scope="col">SAIFI In A Feeder</th>
                <th scope="col">SAIDI</th>
                <th scope="col">SAIFI</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row">1</th>
                <td>Mark</td>
                <td>Otto</td>
                <td>@mdo</td>
                <td>Mark</td>
                <td>Otto</td>
                <td>@mdo</td>
                <td>Mark</td>
                <td>Otto</td>

              </tr>

            </tbody>
          </table>

    </div>
  </div>
</div>


{% endblock content %}

infoproject/templates/result.html
{% extends 'base.html' %}
{% block content %}

{{duration}}
{{count}}
<div class="container">
  <div class="row">
    <div class="col-6 m-auto">

      
          <form method="POST" action="{% url 'infoapp:meter-data-calculation' %}">
            {% csrf_token %}
            <div class="form-group">
              <label for="exampleInputEmail1">Month:</label>
              <input type="text" name="month" class="form-control" id="exampleInputEmail1"  required placeholder="Please enter month">
              <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Year:</label>
              <input type="text" name="year" class="form-control" id="exampleInputEmail1"  required placeholder="Please enter year">
              <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
            </div>

            <br>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>

          <br>

    </div>
  </div>
</div>

<!-- <div class="container mt-5">
    <div class="row">
        <div class="col">
            <table class="table table-striped table-width">

                <tbody>
                  <tr>
                    <th scope="row">1</th>
                    <td>Total Interuption</td>
                    <td>
                        
                        {{count}} Nos
                    </td>
                    
                  </tr>
                  <tr>
                    <th scope="row">2</th>
                    <td>Total Duration:</td>
                    <td>
                        {{duration}} Minute
                    </td>
                 
                  </tr>
            
                </tbody>
              </table>
        </div>
    </div>
</div> -->


{% endblock content %}

infoproject/templates/upload-history.html
{% extends 'base.html' %}
{% block content%}

<div class="container">
  <div class="row">
    <div class="col-6 m-auto">
      






        <table class="table">
            
              <tr>
                <th scope="col">#</th>
                <th scope="col">Substation</th>
                <th scope="col">Feeder</th>
                <th scope="col">Data</th>
              </tr>
          {% for data in data %}
              <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{data.substation_name}}</td>
                <td>{{data.feeder_no}}</td>
                <td></td>
              </tr>
            {% endfor %}
          </table>

    </div>
  </div>
</div>

{% endblock %}

infoproject/templates/upload.html
{% extends 'base.html' %}
{% block content%}

<div class="container">
  <div class="row">
    <div class="col-6 m-auto">
                {% if msg2 %}
          <div class="alert alert-success" role="alert">
              {{msg2}}
          </div>
          {% endif %}
          <br>

          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            

            <p>Data: <input type="file" name="myfile" required></p>
            <button class="btn btn-secondary" type="submit">Upload</button>
          </form>
          <br>

    </div>
  </div>
</div>

{% endblock %}

infoproject/templates/user_login.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>
<body>
    {% if msg1 %}
    {{ msg1 }}
    {% endif %}


<div class="container mt-5">
    <div class="row ">
        <div class="col-md-4 m-auto">
            <div class="card rounded shadow shadow-sm">
                <div class="card-header">
                    <h3 class="mb-0">Login</h3>
                </div>
                <div class="card-body">
                    <form class="form" role="form" autocomplete="off" id="formLogin" novalidate="" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="uname1">Username</label>
                            <input type="text" class="form-control form-control-lg rounded-0" name="uname1" id="uname1" required="">
                            <div class="invalid-feedback">Oops, you missed this one.</div>
                        </div>
                        <div class="form-group">
                            <label>Password</label>
                            <input type="password" class="form-control form-control-lg rounded-0" name="pwd1" id="pwd1" required="" autocomplete="new-password">
                            <div class="invalid-feedback">Enter your password too!</div>
                        </div>
                        <div>
                            <label class="custom-control custom-checkbox">
                              <input type="checkbox" class="custom-control-input">
                              <span class="custom-control-indicator"></span>
                              <span class="custom-control-description small text-dark"><a href="#">Forgot Password?</a></span>
                              <button type="submit" class="btn btn-dark btn-lg float-right" id="btnLogin">Login</button>
                            </label>
                           
                            
                        </div>
                        
                    </form>
                </div>
                <!--/card-block-->
            </div>
        </div>
    </div>
</div>